
server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpadb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: pjm
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # ????

  devtools:
    livereload:
      enabled: true
